# SLSA configuration for Go releaser
version: 1

# Simple configuration that focuses on a single build
builds:
  - id: mock-harbor
    binary: mock-harbor
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{.Version}}

# Archive settings (optional)
archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: binary

# Define metadata about this release
release:
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"

# Checksum settings
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Where to publish artifacts
release:
  # Don't use draft mode when publishing releases
  draft: false
  # Wait for manual validation before publishing release
  prerelease: false
  # Define metadata about this release
  name_template: "{{.Tag}}"

# Checksum settings
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Sign the checksums file
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    args: ["sign-blob", "--output", "${signature}", "${artifact}"]
    artifacts: checksum
