name: SLSA Go Release

on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  # Build job to create the binaries using our Makefile
  build:
    runs-on: ubuntu-24.04
    name: Build binaries
    outputs:
      digests: ${{ steps.hash.outputs.digests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true
      
      - name: Build cross-platform binaries
        run: |
          make release
      
      - name: List built artifacts
        run: ls -la dist/
        
      - name: Generate artifacts hash
        id: hash
        run: |
          # Generate hash information
          cd dist
          echo "digests=$(sha256sum mock-harbor-* | base64 -w0)" >> $GITHUB_OUTPUT
      
      # Upload artifacts to release if triggered by a release
      - name: Upload artifacts to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/mock-harbor-darwin-amd64
            dist/mock-harbor-darwin-arm64
            dist/mock-harbor-linux-amd64
            dist/mock-harbor-linux-arm64
            dist/SHA256SUMS

  # SLSA provenance generation as a separate reusable workflow job
  provenance:
    needs: [build]
    permissions:
      id-token: write    # Required for SLSA provenance
      contents: write    # Required for writing to releases
      actions: read      # Required for detecting the Github workflow
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.5.0
    with:
      go-version-file: "go.mod"  # Use go.mod to determine Go version
      evaluated-envs: "GITHUB_REPOSITORY,GITHUB_REF"
      upload-assets: true         # Upload provenance to GitHub release
